### ISSUE TITLE
ngrok startup fails

### ISSUE THREAD

**Issue by beckmx** [actions-on-google/smart-home-nodejs#431]
Hello, I noticed that the local build stopped working, maybe something related to ngrok api changes

**Comment by Fleker** [comment]
Has Ngrok changed recently? The dependency is pinned at 2.3.x, which shouldn't affect the API. Does it throw an error or just not load the pages?

**Comment by veonua** [comment]
just start it manually

>npm run start
>ngrok http 3000

**Comment by Fleker** [comment]
Are you running both `npm run start` and `ngrok http 3000`?

What if you run `npm run start:local`? That seems to work for me.

**Comment by beckmx** [comment]
with start:local I had the issue, with http 3000, I didnt, however I setup a domain :p to avoid tunneling

**Comment by veonua** [comment]
Smart home server listening at :::3000
Ngrok was unable to start
{ Error: ngrok is not yet ready to start tunnels
    at Request._callback (/home/veon/work/smart-home-nodejs/node_modules/ngrok/index.js:192:30)
    at Request.self.callback (/home/veon/work/smart-home-nodejs/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/veon/work/smart-home-nodejs/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/veon/work/smart-home-nodejs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  error_code: 104,
  status_code: 503,
  msg: 'ngrok is not yet ready to start tunnels',
  details: 
   { err: 'a successful ngrok tunnel session has not yet been established' } }

but as I said 
> ngrok http 3000
in second terminal works like a charm

**Comment by Fleker** [comment]
I don't know why that's happening, as I can't reproduce it on my system. It just works fine.

**Comment by LIULi-VVET** [comment]
I have the same experience.
bit unfortunately it I can only surf the Internet through Shadowsocks a proxy my port .
Set up `set http_proxy=http://localhost:3000` for CMD consloe.
Is this the cause?
