### ISSUE TITLE
Failing with implicit grand type

### ISSUE THREAD

**Issue by vppillai** [actions-on-google/smart-home-nodejs#44]
I tried to run the setup using implicit grand instead of Authorization code grand and I get the below error in the console:

```
TypeError: res.error is not a function
    at /home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/cloud/auth-provider.js:164:18
    at Layer.handle [as handle_request] (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/layer.js:95:5)
    at /home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/vysakh/temp/googleActions/actionssdk-smart-home-nodejs/smart-home-provider/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:77:13)
GET /oauth?response_type=token&client_id=ZxjqWpsYj3&redirect_uri=https://oauth-redirect.googleusercontent.com/r/project-4774743446309170936&scope=profile&state=Cu8CQUZEXzV0bkFaZ285eXNLWnN0WXZ2OV9vOHZsQ0tKSXExbTRfLUpseGhCa2luUlc2Ujc1R1RrbURVRDJxNlRsQlJfUHN5bXRyWklTTDRXblZrcDc4NVA1MVVIclpjN2g2d2cxbFhrejJjcldLd2x1TmQweEpTeEp5d2dLMXdDcElpYzJ1RjRjRmVHNWhWTTczLUhMbWZjNmRGRDFIVG12QlV3cXQzem8wb3hzWU5NTUU2SVhaOTdpMzdudU1BUkl4WFN1eUtOajFuOUNZZE1KZGpudUlCMXl0bTVDQ0huT3RhMVhHSm9BVV9USExWeXlQcHIxR05lbmFadHhmR3BmQXlHcHMybnFLaUR4SXh3MDNsemlyWmV6eXBMUkt1eEdlcjdKOEFSYUNLY2drWFJUTm13aVZZc2NJNG5CWDItS3kyQW9kTmFOM2l0X054WU9RN0RmQ0Z0dUJGS1dYNWpqamdhMFBqaFh0MjNScHFtdxIcYXNzaXN0YW50LWhhbmRvZmY6Ly9jb21wbGV0ZSJKaHR0cHM6Ly9vYXV0aC1yZWRpcmVjdC5nb29nbGV1c2VyY29udGVudC5jb20vci9wcm9qZWN0LTQ3NzQ3NDM0NDYzMDkxNzA5MzYqGWFjdGlvbnN0ZXN0dXNlckBnbWFpbC5jb20yH3Byb2plY3QtNDc3NDc0MzQ0NjMwOTE3MDkzNl9kZXY 500 2.608 ms - 1668
```

**Comment by Fleker** [comment]
You do need to use Authorization Code grant for the sample to work.

But I'll leave this open and see if we can present a more useful error message.

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
