### ISSUE TITLE
Errors Connecting Firebase

### ISSUE THREAD

**Issue by Anonymike** [actions-on-google/smart-home-nodejs#448]
Hi! I believe I followed the tutorial correctly. I'm able to sign get past auth in the google assistant, but in the console I'm seeing this. Perhaps I misconfigured the firebase project? 🤔 

```
POST /smarthome 500 24.482 ms - 105
2019-08-24 17:31:07 default[20190824t122605]  Error: 9 FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.      at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)      at ClientReadableStream._emitStatusIfDone (/srv/node_modules/grpc/src/client.js:233:26)      at ClientReadableStream._receiveStatus (/srv/node_modules/grpc/src/client.js:211:8)      at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1272:15)      at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)      at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)      at /srv/node_modules/grpc/src/client_interceptors.js:1029:24
```

**Comment by Anonymike** [comment]
Nvm I had to generate the firebase admin key and add it the the src/ directory
