### ISSUE TITLE
Google Smart Home Device Addition From Partner Cloud

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#467]
Hi after submitting home app for certification google raised this issue with our service.

**Add a device in the partner application.**
**Changes occur automatically and updates are reflected in the Google home app.  Changes should occur without a pull down/manual refresh.  Closing and reopening GHA however is valid.**

How can we push device add/edit/delete from our cloud to google cloud. Is it the same as report state. Can anyone please post the sample json.???

**Comment by Fleker** [comment]
In your case, you should implement [request sync](https://developers.google.com/actions/smarthome/develop/request-sync) when a device is added or removed.

**Comment by raju102** [comment]
Thanks .It worked..

**Comment by raju102** [comment]
when trying to set up report state dashboard i am getting an error like this
Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

what could be the issue

**Comment by Fleker** [comment]
It's not clear where the issue is happening. It builds fine for me on Ubuntu, and deploys without error to Google App Engine.

**Comment by raju102** [comment]
One feedback we got after submission is **Grouped devices appear after linking. All device grouping should occur only through user interaction with Google Home.**
In our platform we have a group concept, where we can add devices to it. For a user in our platform using google home if he has multiple groups with many devices, during device discovery now thos groups will also be listed in google home app. If we avoid this group during discovery it would be difficult for the user to again create a group using GHA..Is it mandatory that we should remove group listing during discovery

**Comment by raju102** [comment]
device.proto:39:3: "google.home.graph.v1.DeviceNames" seems to be defined in "google/home/graph/v1/device.proto", which is not imported by "device.proto".  To use it here, please add the necessary import.
device.proto:53:3: "google.home.graph.v1.DeviceInfo" seems to be defined in "google/home/graph/v1/device.proto", which is not imported by "device.proto".  To use it here, please add the necessary import.
device.proto:69:12: "google.home.graph.v1.AgentOtherDeviceId" seems to be defined in "google/home/graph/v1/device.proto", which is not imported by "device.proto".  To use it here, please add the necessary import.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.411 s
[INFO] Finished at: 2019-10-11T11:48:06+05:30
[INFO] Final Memory: 16M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project dashboard: protoc did not exit cleanly. Review output for more information. -> [Help 1]


Getting this error when building the server for smart home dashboard

**Comment by raju102** [comment]
i was able to configure the server part. But the web ui part is throwing an error

chunk {0} styles.8a126321729b8c0aa334.bundle.css (styles) 46.9 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in : Can't bind to 'ng-show' since it isn't a known property of 'img'. ("gStyle]="{'background-color':device.updated ? 'green' : '#424242' }">

        <img mat-list-avatar [ERROR ->]ng-show="{{device.giphyUrl}}" src="{{device.giphyUrl}}" alt="{{device.name}}">
        <i mat-list-av")
: Can't bind to 'ng-show' since it isn't a known property of 'i'. ("giphyUrl}}" alt="{{device.name}}">
        <i mat-list-avatar class="material-icons md-48 md-light" [ERROR ->]ng-show="{{!device.giphyUrl}}">{{device.icon}}</i>
        <h3 mat-line class='device-name'>{{device.")

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.0.0 build: `ng build --prod && cp -r ../appengine/* ../webapp/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raju/.npm/_logs/2019-10-11T09_34_07_113Z-debug.log

**Comment by raju102** [comment]
Hi i was able to configure the web ui and the server part for report state dashboard, but after i upload the json file and enter the agentUserId i am getting exception from the server


java.lang.NullPointerException: null
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191) ~[google-http-client-1.19.0.jar!/:1.19.0]
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127) ~[google-http-client-1.19.0.jar!/:1.19.0]
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:158) ~[google-auth-library-oauth2-http-0.9.0.jar!/:na]
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:141) ~[google-auth-library-oauth2-http-0.9.0.jar!/:na]
	at com.google.homegraph.dashboard.controller.HomeGraphController.createConnection(HomeGraphController.java:97) ~[classes!/:na]
	at com.google.homegraph.dashboard.controller.HomeGraphController.getHomegraph(HomeGraphController.java:78) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.27.jar!/:8.5.27]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

**Comment by raju102** [comment]
Request URL: http://localhost:8080/homegraph?agentUserId=7&file=WiSilica%20Smart-af44a05ad1ad.json
Request Method: GET
Status Code: 500 
Remote Address: [::1]:8080




Response

{"timestamp":1571117741584,"status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":"No message available","path":"/homegraph"}

**Comment by raju102** [comment]
it worked with Using Google App Engine. But when i build i was not getting app.yaml file. i got it from one of the response posted in the fourm.

**Comment by raju102** [comment]
One feedback we got after submission is Grouped devices appear after linking. All device grouping should occur only through user interaction with Google Home.
In our platform we have a group concept, where we can add devices to it. For a user in our platform using google home if he has multiple groups with many devices, during device discovery now thos groups will also be listed in google home app. If we avoid this group during discovery it would be difficult for the user to again create a group using GHA..Is it mandatory that we should remove group listing during discovery

please comment on this one

**Comment by raju102** [comment]
Grouped devices appear after linking. All device grouping should occur only through user interaction with Google Home.
Unable to retrieve AgentUserID for ReportState validation. 
This is the feedback which i got after submission How can i test this issue?

**Comment by proppy** [comment]
This sounds like an issue w/ certification of your smarthome action, and not something specific to the sample code hosted in this repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
