### ISSUE TITLE
Error: An API key was not specified. 

### ISSUE THREAD

**Issue by LindaLawton** [actions-on-google/smart-home-nodejs#495]
```
Error: An API key was not specified. Please visit https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview

{ userId: '1234', deviceId: '1dnw', localDeviceId: null }
Error: 5 NOT_FOUND: No document to update: projects/zensehome-16e93/databases/(default)/documents/users/1234/devices/1dnw
    at Object.exports.createStatusError (/home/linda/development/smart-home-nodejs/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/linda/development/smart-home-nodejs/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/linda/development/smart-home-nodejs/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/linda/development/smart-home-nodejs/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/linda/development/smart-home-nodejs/node_modules/grpc/src/client_interceptors.js:845:24) {
  code: 5,
  metadata: Metadata { _internal_repr: {} },
  details: 'No document to update: projects/zensehome-16e93/databases/(default)/documents/users/1234/devices/1dnw'
}
POST /smarthome/update 400 214.572 ms - 144
Error: An API key was not specified. Please visit https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview
    at Function.<anonymous> (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:158:19)
    at Generator.next (<anonymous>)
    at /home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:18:12)
    at Function.requestSync (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:147:16)
    at Object.<anonymous> (/home/linda/development/smart-home-nodejs/dist/index.js:237:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/linda/development/smart-home-nodejs/dist/index.js:17:58)
POST /smarthome/create 200 264.132 ms - 2
Error: An API key was not specified. Please visit https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview
    at Function.<anonymous> (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:158:19)
    at Generator.next (<anonymous>)
    at /home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:18:12)
    at Function.requestSync (/home/linda/development/smart-home-nodejs/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:147:16)
    at Object.<anonymous> (/home/linda/development/smart-home-nodejs/dist/index.js:203:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/linda/development/smart-home-nodejs/dist/index.js:17:58)
POST /smarthome/update 400 219.818 ms - 148
https://oauth-redirect.googleusercontent.com/r/zensehome-16e93?code=xxxxxx&state=AB8b_TO8Y8q8MhGOBcxXnD3hrY2JxIeArefIP4sRNECdc-CE70X4KWXBv7MVDnOaR6q462zwcuUDVqDGdgXIwlS7jEfSrbLlwJkHTFZ9xPPdv3rWVU3-X24WnGJ6N-QjNh-s_9zzXbKMlgj-LZubusKbv2aGRJYuykvOEKIMFDvtP8FZI4ALHMc0o5tVeldl9ItZ5oUKKMfkWTbASVEXareN1RQSCY6smRpJB4P93fuEOoNxeseL8z_dfJiAt_A15xkQOqYT2mz0fX-Zu1aNW_JNIH0sQpcqulu0vmBXNZyUBVQC_CKjYr2ToRDzRkDFqgXtqPfzvqnWXgpDrwCbsdCvBacMvzc4Vzfjmf_-jXzJwthRL2fwsejIkCruC-uQAWZAjiR8dhu4XVFWSB7wqlh51ArwzTgL4nuCDqsTZF54e1tmLU8chw7qXso550ZktiAGspIigdotiJ4XMKHm9Wpctohy3r2zT4pYoI-2qPfxiEzrrt2gNiLmX9Dsie0SpR-lfpotKocAbuCYB6anfdXhbeknL_cJVbO0lqmZL3zEGmZiyXeyvH_mOLXizPtXzKvozC10InWT
GET /fakeauth?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fzensehome-16e93&client_id=sampleClientId&response_type=code&state=AB8b_TO8Y8q8MhGOBcxXnD3hrY2JxIeArefIP4sRNECdc-CE70X4KWXBv7MVDnOaR6q462zwcuUDVqDGdgXIwlS7jEfSrbLlwJkHTFZ9xPPdv3rWVU3-X24WnGJ6N-QjNh-s_9zzXbKMlgj-LZubusKbv2aGRJYuykvOEKIMFDvtP8FZI4ALHMc0o5tVeldl9ItZ5oUKKMfkWTbASVEXareN1RQSCY6smRpJB4P93fuEOoNxeseL8z_dfJiAt_A15xkQOqYT2mz0fX-Zu1aNW_JNIH0sQpcqulu0vmBXNZyUBVQC_CKjYr2ToRDzRkDFqgXtqPfzvqnWXgpDrwCbsdCvBacMvzc4Vzfjmf_-jXzJwthRL2fwsejIkCruC-uQAWZAjiR8dhu4XVFWSB7wqlh51ArwzTgL4nuCDqsTZF54e1tmLU8chw7qXso550ZktiAGspIigdotiJ4XMKHm9Wpctohy3r2zT4pYoI-2qPfxiEzrrt2gNiLmX9Dsie0SpR-lfpotKocAbuCYB6anfdXhbeknL_cJVbO0lqmZL3zEGmZiyXeyvH_mOLXizPtXzKvozC10InWT&user_locale=en-US 302 1.190 ms - 1390
https://oauth-redirect.googleusercontent.com/r/zensehome-16e93?code=xxxxxx&state=AB8b_TOepEEkD8t1L0-0ihPOnXcwaxEXpo7FOPVLT6oIUn-x0VBTDAg-Q26LY_LXsEA-PYbU7qusg_hIA7HX6690UkF-bGc9k5_jlBw_W_OD1HhSbHPKjFD2OGWNcEOGtTWHSHzBWPVMBBSSu993rbw2v7xthwX7j_Gu4LBZ1qwLRgJeIB1CdG_v72CGUymqcHau1R9OdRduk8z2OsS_JHR09lF_T6WYL2hYnX4j2UKqWLAkBrAyg2IFmXWWN7vg240CcKKRMjxsTlOzmXRj0XEcQuwDUREc7b0oOdRbHhNu8b9PUWk0FuSJ-wNbscrwU754fwUSEohjQwr4yAH0yy3PlRAWOnp4Jc2sIruowrEWuMLbxNLMaXpXVlc8bGAFJG-AMN5I_ysDgSclxn8UVlmV73K_8m5PI7FhjMtJZIb16l7kaH9MDae_UQWtpJkp2PqP4Z1ukcIHrHs6gHuHBYVXRvmRN1iQdbPv-AGp2wr0kfwFn5tg2ooHMCkpBCjE1daIF-M0YOLRESNNbvvQdvrtgt0WiU4vMJDSUB5B4jQyWP4xK4YFhUTQJoEdFXtnUa36Q4viwTvT
GET /fakeauth?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fzensehome-16e93&client_id=sampleClientId&response_type=code&state=AB8b_TOepEEkD8t1L0-0ihPOnXcwaxEXpo7FOPVLT6oIUn-x0VBTDAg-Q26LY_LXsEA-PYbU7qusg_hIA7HX6690UkF-bGc9k5_jlBw_W_OD1HhSbHPKjFD2OGWNcEOGtTWHSHzBWPVMBBSSu993rbw2v7xthwX7j_Gu4LBZ1qwLRgJeIB1CdG_v72CGUymqcHau1R9OdRduk8z2OsS_JHR09lF_T6WYL2hYnX4j2UKqWLAkBrAyg2IFmXWWN7vg240CcKKRMjxsTlOzmXRj0XEcQuwDUREc7b0oOdRbHhNu8b9PUWk0FuSJ-wNbscrwU754fwUSEohjQwr4yAH0yy3PlRAWOnp4Jc2sIruowrEWuMLbxNLMaXpXVlc8bGAFJG-AMN5I_ysDgSclxn8UVlmV73K_8m5PI7FhjMtJZIb16l7kaH9MDae_UQWtpJkp2PqP4Z1ukcIHrHs6gHuHBYVXRvmRN1iQdbPv-AGp2wr0kfwFn5tg2ooHMCkpBCjE1daIF-M0YOLRESNNbvvQdvrtgt0WiU4vMJDSUB5B4jQyWP4xK4YFhUTQJoEdFXtnUa36Q4viwTvT&user_locale=en-US 302 1.255 ms - 1390
```

**Comment by proppy** [comment]
This is likely related to missing credentials due to a miss-configuration, can you provide more details about the condition creating this error?

**Comment by LindaLawton** [comment]
As i posted this issue six months ago and probably not.   Might as well close.
