### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by ervinnotari** [actions-on-google/smart-home-nodejs#528]
I have the following error when deploying:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle smart-home-app-sample@0.0.1~predeploy: smart-home-app-sample@0.0.1
6 info lifecycle smart-home-app-sample@0.0.1~deploy: smart-home-app-sample@0.0.1
7 verbose lifecycle smart-home-app-sample@0.0.1~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle smart-home-app-sample@0.0.1~deploy: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\320099353\Desktop\Projetinhos\smart-home-nodejs\node_modules\.bin;C:\Users\320099353\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\320099353\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\oracle\product\10.2.0\client\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.8.0_101\bin;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Adaptiva\AdaptivaClient\bin\x32;C:\Program Files (x86)\Adaptiva\AdaptivaClient\bin\x64;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Users\320099353\AppData\Local\Microsoft\WindowsApps;C:\Users\320099353\AppData\Roaming\npm;C:\Users\320099353\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle smart-home-app-sample@0.0.1~deploy: CWD: C:\Users\320099353\Desktop\Projetinhos\smart-home-nodejs
10 silly lifecycle smart-home-app-sample@0.0.1~deploy: Args: [ '/d /s /c', 'firebase deploy' ]
11 silly lifecycle smart-home-app-sample@0.0.1~deploy: Returned: code: 1  signal: null
12 info lifecycle smart-home-app-sample@0.0.1~deploy: Failed to exec deploy script
13 verbose stack Error: smart-home-app-sample@0.0.1 deploy: `firebase deploy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid smart-home-app-sample@0.0.1
15 verbose cwd C:\Users\320099353\Desktop\Projetinhos\smart-home-nodejs
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error smart-home-app-sample@0.0.1 deploy: `firebase deploy`
22 error Exit status 1
23 error Failed at the smart-home-app-sample@0.0.1 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by proppy** [comment]
can you retry with a more recent version of Node.js?

**Comment by proppy** [comment]
I suspect this is related to https://github.com/actions-on-google/smart-home-nodejs/issues/533, the samples depends on Node >= 10 and firebase functions now requires billing to be enabled.
